### ISSUE TITLE
flick_video_player version is depricated and cause conflict with provider v6

### ISSUE THREAD

**Issue by mk42** [Mindinventory/vimeo_video_player#1]
> flutter pub add vimeo_video_player
`Because flutter_bloc >=7.2.0 depends on provider ^6.0.0 and flick_video_player >=0.2.0 <0.4.0-dev.4 depends on provider ^5.0.0, flutter_bloc >=7.2.0 is incompatible with flick_video_player >=0.2.0 <0.4.0-dev.4.
And because every version of vimeo_video_player depends on flick_video_player ^0.3.1, flutter_bloc >=7.2.0 is incompatible with vimeo_video_player.
So, because digitaler depends on both flutter_bloc ^7.3.3 and vimeo_video_player any, version solving failed.`
https://github.com/GeekyAnts/flick-video-player/issues/139

**Comment by sagarfaldu17** [comment]
@mk42 
Fix the issue and Complete the changes in the last push.
It's fixed in version 0.0.3.
