### ISSUE TITLE
LateInitializationError: Field '_videoPlayerController@2932358648' has not been initialized.

### ISSUE THREAD

**Issue by akshay-appinventiv** [Mindinventory/vimeo_video_player#14]
Getting this error few times not sure what to initialize 

using `vimeo_video_player : 0.0.6`

got this exception 

**When the exception was thrown, this was the stack: 
#0      _VimeoVideoPlayerState._videoPlayerController (package:vimeo_video_player/src/vimeo_player.dart)
#1      _VimeoVideoPlayerState.deactivate (package:vimeo_video_player/src/vimeo_player.dart:91:5)
#2      StatefulElement.deactivate (package:flutter/src/widgets/framework.dart:4976:11)
#3      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1944:13)
#4      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6271:14)
#5      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1946:13)
#6      MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6386:16)
#7      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1946:13)**

**Comment by mohit-chauhan-mi** [comment]
@akshay-appinventiv Can you please share more details on this

**Comment by akshay-appinventiv** [comment]
@deep-mindinventory this was happening when i have multiple players in a single screen

**Comment by deep-mindinventory** [comment]
same as #22
