### ISSUE TITLE
type 'double' is not a subtype of type 'int?'

### ISSUE THREAD

**Issue by PCardosoAlpha** [Mindinventory/vimeo_video_player#20]
When trying to use the vimeo link: "https://vimeo.com/184825484"

I get the following error without the video playing:

[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: type 'double' is not a subtype of type 'int?'
#0      new VimeoProgressive.fromJson
vimeo_video_config.dart:52
#1      new VimeoFiles.fromJson.<anonymous closure>
vimeo_video_config.dart:25
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#3      ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#4      new List.from (dart:core-patch/array_patch.dart:42:17)
#5      new VimeoFiles.fromJson
vimeo_video_config.dart:23
#6      new VimeoRequest.fromJson
vimeo_video_config.dart:14
#7      new VimeoVideoConfig.fromJson
vimeo_video_config.dart:5
#8      _VimeoVideoPlayerState._getVimeoVideoConfig
vimeo_player.dart:240
<asynchronous suspension>
#9      _VimeoVideoPlayerStat<…>

This happens on both iOS and Android simulator and the error is found in the vimeo_vido_config.dart file.

**Comment by mohit-chauhan-mi** [comment]
@PCardosoAlpha Fixed this check it with the latest [version](https://pub.dev/packages/vimeo_video_player/versions/0.0.8)
