### ISSUE TITLE
video play  issue

### ISSUE THREAD

**Issue by alpeshbrainstream** [Mindinventory/vimeo_video_player#21]
video play to not show video properly and background in voice play continue
Please test iPhone 11 to up iPhones

**Comment by alpeshbrainstream** [comment]
Hello @mohit-chauhan-mi 
How much time in fixed this issue?

**Comment by mohit-chauhan-mi** [comment]
@alpeshbrainstream I'm working on it update you soon...

**Comment by mohit-chauhan-mi** [comment]
@alpeshbrainstream Fixed this check it with the latest [version](https://pub.dev/packages/vimeo_video_player/versions/0.0.8)
