### ISSUE TITLE
Multiple videos landscape to portrait

### ISSUE THREAD

**Issue by alpeshbrainstream** [Mindinventory/vimeo_video_player#22]
Hello @mohit-chauhan-mi  
I have one issue find for your package
multiple videos show in first video full screen to back work properly but another video full screen to not show properly please this issue fixed.

![simulator_screenshot_A9867468-B241-4A83-B703-C2880A98C1BB](https://user-images.githubusercontent.com/95357903/229030509-921932f4-a75a-4351-a115-0b6d4e0d7fd1.png)

**Comment by alpeshbrainstream** [comment]
and this issue facing in debug console
![Screenshot 2023-03-31 at 11 00 58 AM](https://user-images.githubusercontent.com/95357903/229031523-65f5ea82-b50d-479e-8a56-42857c3d3b75.png)

**Comment by mohit-chauhan-mi** [comment]
Please check it with the latest [version](https://pub.dev/packages/vimeo_video_player/versions/0.0.9)
