### ISSUE TITLE
'String?' can't be assigned to the parameter type 'Object'

### ISSUE THREAD

**Issue by PCardosoAlpha** [Mindinventory/vimeo_video_player#26]
Hello

When I try to run your example code in a new project I get the following error:

![Screenshot 2023-05-30 at 09 34 30_](https://github.com/Mindinventory/vimeo_video_player/assets/112711624/439da19c-d6b5-4eb1-9cb7-33552d002b97)

This error appears when you try to start the application with the import of the vimeo_video_player library on either the iOS or Android simulator.

Running this on Flutter Channel stable 3.10.2.

Let me know if you require more information.

**Comment by mohit-chauhan-mi** [comment]
@PCardosoAlpha 
I think this issue is with the **universal_html** package not with the **vimeo_video_player** can you please check by removing this package **universal_html**.

Let me know if this works, Thanks.

**Comment by PCardosoAlpha** [comment]
Hi @mohit-chauhan-mi 

While I couldn't remove the universal_html package from the vimeo_video_player (as it is registered as a dependancy) I could however install the universal_html package on a clean project and found the same error.

Can your package, the vimeo_video_player, run without the universal_html or do we have to wait for an update to the universal_html package before the vimeo_video_player package will be able to work again?

**Comment by mohit-chauhan-mi** [comment]
@PCardosoAlpha let me check on this I'll update you.

**Comment by mohit-chauhan-mi** [comment]
@PCardosoAlpha I'm not able to reproduce this issue. I've checked with the new Flutter project using the Flutter stable channel 3.10.3 and 3.10.0. 

It seems that the problem is with the pub cache, please try with the **flutter clean** command or delete the .pub-cache folder and then do the **flutter pub get** command.

Let me know if this helps or not, Thanks.

**Comment by PCardosoAlpha** [comment]
It has seemed to resolved itself. Either with the latest update to flutter or by some other means.

Thank you for your effort in looking into this matter!
