### ISSUE TITLE
Support for Privacy settings

### ISSUE THREAD

**Issue by akshaybengani** [Mindinventory/vimeo_video_player#27]
In the repository, I didn't find any implementation to take passwords for videos which are password restricted, 
I want to build a solution where I can show videos to the user app, and that video cannot be accessed outside the application, as such I cant use public and unlisted video links.
And similarly I don't want to show a password box to user, it should be in the application login only.

Check this link for more information on Vimeo Privacy settings
https://help.vimeo.com/hc/en-us/articles/12426199699985-Overview-of-video-privacy-settings

**Comment by mohit-chauhan-mi** [comment]
similar to #15

**Comment by Joseph-Nathan** [comment]
@akshaybengani do you found any solution ?

**Comment by akshaybengani** [comment]
Their Android, IOS, and Flutter plugins, are based on the public API available by Vimeo. In the public API documentation, there is no support for password-restricted video sharing, So unfortunately there is no current solution.

**Comment by Joseph-Nathan** [comment]
is there alternative way for password-restricted video sharing to secure the video !
