### ISSUE TITLE
App crach pressed back button 

### ISSUE THREAD

**Issue by Alfredo2022f** [Mindinventory/vimeo_video_player#29]
i have an app whit multiples screen , when select video section play the video , but when i pressed button back , the app crach

error 1:

FlutterError (A VideoPlayerController was used after being disposed.
Once you have called dispose() on a VideoPlayerController, it can no longer be used.)

error 2

FlutterError (setState() or markNeedsBuild() called during build.
This _InheritedProviderScope<FlickVideoManager?> widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was:
  _InheritedProviderScope<FlickVideoManager?>
The widget which was currently being built when the offending call was made was:
  Container)

**Comment by Alfredo2022f** [comment]
can you send me email to dude 

alfredo@honeymustard.mx

**Comment by phankietit** [comment]
Fixed on this [PR](https://github.com/Mindinventory/vimeo_video_player/pull/30)

**Comment by mohit-chauhan-mi** [comment]
Merged the PR [#30](https://github.com/Mindinventory/vimeo_video_player/pull/30) thanks to [phankietit](https://github.com/phankietit). Please check it with the [latest version](https://pub.dev/packages/vimeo_video_player). Thanks.

**Comment by zoelounge** [comment]
Excuse me the are the same problem on web:

The following assertion was thrown while finalizing the widget tree:
A WebPlatformInAppWebViewController was used after being disposed.
Once the WebPlatformInAppWebViewController has been disposed, it can no longer be used.
