### ISSUE TITLE
How to play private video, need help?

### ISSUE THREAD

**Issue by Deepsonstha** [Mindinventory/vimeo_video_player#32]

**Comment by jaydeepkaria-mi** [comment]
Hello @Deepsonstha, did you mean you want to play private vimeo video using id?

**Comment by mohit-chauhan-mi** [comment]
similar to #15 and #27

**Comment by mohit-chauhan-mi** [comment]
Closing this issue for now, Thanks.

**Comment by mohit-chauhan-mi** [comment]
@Deepsonstha I recommend checking out this [link](https://developer.vimeo.com/api/reference) for more details on playing private videos.
