### ISSUE TITLE
Video URL not working

### ISSUE THREAD

**Issue by esaiamuthan** [Mindinventory/vimeo_video_player#36]
Hello

Am having the vimeo url link like this

https://player.vimeo.com/video/**videoId**

https://player.vimeo.com/video/**videoId**?dnt=1&app_id=**appId**

When i try to load this player is not working

![image](https://github.com/Mindinventory/vimeo_video_player/assets/46670541/2c9a3e05-3742-4ab2-90f6-4f61ae5d28a2)

**Comment by pratikkansaramind** [comment]
@esaiamuthan Thank you for expressing your confidence in our team. It would be a great help if you can share more insights to your concern and We appreciated if you can share exact video URL to get into the root cause. Additionally, we welcome any contributions or insights you may have to improve our package.

**Comment by esaiamuthan** [comment]
https://player.vimeo.com/video/841319969

Hi @pratikkansaramind here is the exact video URL kindly check it and let me know your comments.

I tried using this **(https://vimeo.com/841319969)** it works fine but it should work on above URL i mentioned.

Thanks

**Comment by esaiamuthan** [comment]
Hi @pratikkansaramind we have to implement this feature in our application once it is done kindly update it
Thanks

**Comment by pratikkansaramind** [comment]
@esaiamuthan kindly check with the latest version and let us know the outcome of that.

**Comment by esaiamuthan** [comment]
Am still facing the same problem infinite loading

![image](https://github.com/Mindinventory/vimeo_video_player/assets/46670541/8f5cbd3b-1588-4f23-8d20-8650a4ee25cb)

**Comment by pratikkansaramind** [comment]
@esaiamuthan pls share the callable URL which you are trying.

**Comment by esaiamuthan** [comment]
```
VimeoVideoPlayer(
        // url: 'https://vimeo.com/70591644?height=200',
        url: 'https://player.vimeo.com/video/841319969',
        autoPlay: false,
        startAt: const Duration(seconds: 0),
        onFinished: () {},
        onProgress: (timePoint) {
          print('timePoint $timePoint');
        },
      )
```
here is what am trying

**Comment by pratikkansaramind** [comment]
@esaiamuthan kindly check with the latest version and let us know the outcome of that.

**Comment by esaiamuthan** [comment]
@pratikkansaramind  yes now the video is loading but there is a background related problem came now. Can you please check that also
I will attach the video

https://github.com/Mindinventory/vimeo_video_player/assets/46670541/655f4ca1-8a29-4315-9b04-c4ab6efcfd3d

**Comment by esaiamuthan** [comment]
> @pratikkansaramind yes now the video is loading but there is a background related problem came now. Can you please check that also I will attach the video
> 
>  Screen_recording_20240304_193711.mp4

url: 'https://vimeo.com/841319969',

url: 'https://player.vimeo.com/video/841319969',

Both URL's leads to background issue, need a black background instead of thumbnail background

Thanks

**Comment by pratikkansaramind** [comment]
@esaiamuthan kindly check with the latest version and let us know the outcome of that.

**Comment by esaiamuthan** [comment]
its working fine now thanks
