### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by esaiamuthan** [Mindinventory/vimeo_video_player#37]
* Disable controls play or pause button / firescreen option when i try to customise this in flutter HTML content

* Just load the thumbnails in flutter HTML like YouTube get thumbnail from video-id / URL without any authentication

**Comment by abrarmalekji345** [comment]
@esaiamuthan I don't quite get it what do you want here? Can you please elaborate on this? thanks.

**Comment by jaydeepkaria-mi** [comment]
@esaiamuthan Closing this issue for now. Feel free to open it again if you have queries.
