### ISSUE TITLE
VideoStream.fromJson is broken

### ISSUE THREAD

**Issue by cody-fjorge** [Mindinventory/vimeo_video_player#4]
![VimeoPlayer fromJson issue](https://user-images.githubusercontent.com/65675656/165625853-e5f99798-18b6-421e-a9a6-78a2645d8d7b.png)

VideoStream.id is declared as an int? but the actual value is a string. This is causing the package to not work at all.

**Comment by sagarfaldu17** [comment]
@cody-fjorge 
Fix the issue and Complete the changes in the last push.
It's fixed in version 0.0.3.
