### ISSUE TITLE
video loading issue 

### ISSUE THREAD

**Issue by alpeshbrainstream** [Mindinventory/vimeo_video_player#43]
i have used latest version to fetch some issue but i have resole issue to solution send by email please check and update please

Unhandled Exception: type 'Null' is not a subtype of type 'List<dynamic>' in type cast
#0      new VimeoFiles.fromJson (package:vimeo_video_player/src/model/vimeo_video_config.dart:23:42)
#1      new VimeoRequest.fromJson (package:vimeo_video_player/src/model/vimeo_video_config.dart:14:38)
#2      new VimeoVideoConfig.fromJson (package:vimeo_video_player/src/model/vimeo_video_config.dart:5:46)
#3      _VimeoVideoPlayerState._getVimeoVideoConfig (package:vimeo_video_player/src/vimeo_player.dart:271:41)
<asynchronous suspension>
#4      _VimeoVideoPlayerState._getVimeoVideoConfigFromUrl (package:vimeo_video_player/src/vimeo_player.dart:258:22)
<asynchronous suspension>
#5      _VimeoVideoPlayerState._videoPlayer.<anonymous closure> (package:vimeo_video_player/src/vimeo_player.dart:216:50)
<asynchronous suspension>

**Comment by dirjud** [comment]
I had a player on version 0.0.9 that has worked for years that just started experiencing this issue. I updated to 0.0.15 and have the same failure.

**Comment by jakubjaniec** [comment]
Seems like related to this one: https://github.com/newtaDev/pod_player/issues/182 and here's how they resolved it: https://github.com/newtaDev/pod_player/pull/187.

**Comment by jakubjaniec** [comment]
Issue resolved in 0.0.16. Thanks @jaydeepkaria-mi

**Comment by jaydeepkaria-mi** [comment]
@jakubjaniec Glad to hear that. Closing this issue now.
