### ISSUE TITLE
Error - [null] Dio Error :

### ISSUE THREAD

**Issue by ranmitch99** [Mindinventory/vimeo_video_player#45]
We have used the vimeo_video_player package for some time in our app. Recently more and more Vimeo videos have stopped working. We updated to the lastest version of the package, still this error. As a debugging step we built the most basic of apps to play Vimeo video this error continues. Any suggestions?

**Comment by jaydeepkaria-mi** [comment]
Hi @ranmitch99, Have you tried with the latest version 0.0.16?

**Comment by ranmitch99** [comment]
Yes ... we are using 0.0.16 ... I have noticed in my debugging that we are sending this URL - https://vimeo.com/537511048 to the code but this is being sent by the package - https://player.vimeo.com/video/537511048/config. The error that results is a 403.

**Comment by mfurkanyuceal** [comment]
Same problem

**Comment by maplepam** [comment]
<img width="1512" alt="Screenshot 2024-07-02 at 22 53 58" src="https://github.com/Mindinventory/vimeo_video_player/assets/4180865/cced8e0c-bb0f-49a4-ac0c-5a5fd6a61a9a">

Seems like the /config endpoint having issues. Having same issue as well.

**Comment by jaydeepkaria-mi** [comment]
Currently, the config API is not working for all the videos as earlier. Public video links are working but not private. Will need to look around this.

**Comment by ranmitch99** [comment]
Is there not a solution for what seems to be a change in the way Vimeo is doing things? It looks like the /config endpoint is no longer valid. Does anyone have a suggestion on a different widget to use to play public and embeddable Vimeo content?

**Comment by lrferreiro** [comment]
Same problem!

**Comment by IdirBelmokhtar** [comment]
I have reviewed the Vimeo API documentation and noticed some changes in the API endpoints. You can use the following dependency as a temporary solution, but please note a few conditions I encountered during testing:

- The video IDs used in the URL must support multiple qualities (SD, HD, 720, etc.).

- You need to generate a token from the Vimeo Developer portal and include it in the VimeoVideoPlayer(...) initialization.

`dependencies:`
`  vimeo_video_player:`
`    git:`
`      url: https://github.com/IdirBelmokhtar/vimeo_video_player`

**Comment by edilson14** [comment]
> I have reviewed the Vimeo API documentation and noticed some changes in the API endpoints. You can use the following dependency as a temporary solution, but please note a few conditions I encountered during testing:
> 
>     * The video IDs used in the URL must support multiple qualities (SD, HD, 720, etc.).
> 
>     * You need to generate a token from the Vimeo Developer portal and include it in the VimeoVideoPlayer(...) initialization.
> 
> 
> `dependencies:` ` vimeo_video_player:` ` git:` ` url: https://github.com/IdirBelmokhtar/vimeo_video_player`

i made a fork of this repository and open a pull request with some fix

**Comment by mohit-chauhan-mi** [comment]
The library now uses an InAppWebView to play Vimeo videos, as the public config endpoint of vimeo has been deprecated and is no longer in use.

@ranmitch99 Please check this with the latest [version](https://pub.dev/packages/vimeo_video_player). Thanks.
