### ISSUE TITLE
video not load

### ISSUE THREAD

**Issue by nikunjshaligram** [Mindinventory/vimeo_video_player#46]
my source code :

class VideoPage extends StatelessWidget {
  final String _vimeoVideoUrl = 'https://player.vimeo.com/video/393556569';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Vimeo Video Player'),
      ),
      body: VimeoVideoPlayer(
        url: _vimeoVideoUrl,
        autoPlay: true,
      ),
    );
  }
}

This url is worked fine in browser but not work in flutter application.

my error is: 
E/ExoPlayerImplInternal(17253):       at java.io.RandomAccessFile.<init>(RandomAccessFile.java:289)
E/ExoPlayerImplInternal(17253):       at java.io.RandomAccessFile.<init>(RandomAccessFile.java:152)
E/ExoPlayerImplInternal(17253):       at com.google.android.exoplayer2.upstream.FileDataSource.openLocalFile(FileDataSource.java:184)
E/ExoPlayerImplInternal(17253):       ... 8 more
E/ExoPlayerImplInternal(17253):   Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
E/ExoPlayerImplInternal(17253):       at libcore.io.Linux.open(Native Method)
E/ExoPlayerImplInternal(17253):       at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
E/ExoPlayerImplInternal(17253):       at libcore.io.BlockGuardOs.open(BlockGuardOs.java:273)
E/ExoPlayerImplInternal(17253):       at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
E/ExoPlayerImplInternal(17253):       at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7725)
E/ExoPlayerImplInternal(17253):       at libcore.io.IoBridge.open(IoBridge.java:561)
E/ExoPlayerImplInternal(17253):       ... 11 more

**Comment by Sudesh101999** [comment]
facing same problem

**Comment by MahmoudMagdyEllawatty** [comment]
same problem

**Comment by mohit-chauhan-mi** [comment]
The library now uses an InAppWebView to play Vimeo videos, as the public config endpoint of vimeo has been deprecated and is no longer in use.

@nikunjshaligram Please check this with the latest [version](https://pub.dev/packages/vimeo_video_player). Thanks.
