### ISSUE TITLE
Navigator.pop(context) When video is playing

### ISSUE THREAD

**Issue by NijatNaghiyev** [Mindinventory/vimeo_video_player#48]
If I go back page when video is playing, video isnt stop and keep making sounds. There is no controller to handle.

**Comment by mohit-chauhan-mi** [comment]
@NijatNaghiyev Unfortunately, we are unable to reproduce it with the information provided. Could you please share additional details. Thank you!

**Comment by NijatNaghiyev** [comment]
On iOS while video is playing not full screen, I click back button in AppBar. Audio of video doesn't stop and keep coming audio.

**Comment by mohit-chauhan-mi** [comment]
@NijatNaghiyev We couldn’t reproduce the issue on our end. Could you please check with the latest [version](https://pub.dev/packages/vimeo_video_player), we’ve added InAppWebView callbacks for better event handling, which might help. Let us know if the issue persists. Thank you!

**Comment by mohit-chauhan-mi** [comment]
Closing this for now, Please reopen it if needed. Thanks!
