### ISSUE TITLE
Unhandled Exception: type 'String' is not a subtype of type 'int?'

### ISSUE THREAD

**Issue by asadbekdev** [Mindinventory/vimeo_video_player#5]
![image](https://user-images.githubusercontent.com/67022917/179478238-7f8f04b0-27ea-4a95-ba61-c93934a40689.png)

**Comment by asadbekdev** [comment]
I'm using video video player.
Red one isn't working, green one is working. WHY?

https://vimeo.com/730917679
https://vimeo.com/70591644

**Comment by asadbekdev** [comment]
![image](https://user-images.githubusercontent.com/67022917/179502427-e5a65e86-f8d1-433c-9e06-0bc133beb8a3.png)

**Comment by asadbekdev** [comment]
I think there is problem with typeCasting

**Comment by asadbekdev** [comment]
![image](https://user-images.githubusercontent.com/67022917/179506684-bccb73e9-40e4-4c72-8b12-be1955300ab2.png)

**Comment by asadbekdev** [comment]
I solved the issue, pls convert int to String

**Comment by deep-mindinventory** [comment]
@asadbekdev please check the latest version.
