### ISSUE TITLE
Thumbnails not showing

### ISSUE THREAD

**Issue by bahaahany-eg** [Mindinventory/vimeo_video_player#9]
Hello,
I need to add a thumbnail to the player, but I can't find that option.
Please advice.

**Comment by deep-mindinventory** [comment]
@bahaahany-eg 
We are using video players which have no provision for custom thumbnails. It is loading a thumbnail from the URL. Can you please elaborate more on your usecase?

**Comment by bahaahany-eg** [comment]
I'm using Vimeo to play my videos, but it separates the video & the thumbnail URLs, for example
the video URL: https://vimeo.com/764854978 
Thumbnail URL: https://vumbnail.com/764854978.jpg 
how to mix them in one url

**Comment by deep-mindinventory** [comment]
@bahaahany-eg no such a provision exists in the package. It is loading thumbnails from the URL of the video only. You require to add a custom image with an aspect ratio or something like this.
